name: Deploy Website

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GEEKMAC }}

      - name: Deploy website via SSH
        run: |
          scp -o StrictHostKeyChecking=no -r ./* root@52.221.10.55:/www/wwwroot/geekmac.work.gd
          ssh -o StrictHostKeyChecking=no root@52.221.10.55 'touch /www/wwwroot/geekmac.work.gd/$(date +"%Y-%m-%d_%H-%M-%S").txt'
